<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="franka_asee1">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="franka_asee1" params="connected_to:='' arm_id:='panda' rpy:='0 0 0' xyz:='0 0 0.2484' tcp_xyz:='0 0 0' tcp_rpy:='0 0 0' safety_distance:=0 gazebo:=false description_pkg:=rus_panda_description">
    <xacro:unless value="${connected_to == ''}">
      <joint name="${arm_id}_asee1_joint" type="fixed">
        <parent link="${connected_to}" />
        <child link="${arm_id}_asee1" />
        <origin xyz="${xyz}" rpy="${rpy}" />
      </joint>
    </xacro:unless>

    <xacro:link_with_sc name="asee1" gazebo="${gazebo}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 0.04" direction="y" radius="${0.04+safety_distance}" length="0.1" />
        <xacro:collision_capsule xyz="0 0 0.10" direction="y" radius="${0.02+safety_distance}" length="0.1" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <!-- Define asee1 sensor frames -->
    <!-- <link name="${arm_id}_asee1_tcp" /> -->

    <joint name="${arm_id}_asee1_sensor1_joint" type="fixed">
      <origin xyz="0.058 0 -0.085" rpy="0 -1.570796 0" />
      <parent link="${arm_id}_asee1" />
      <child link="${arm_id}_asee1_sensor1" />
    </joint>
    <link name="${arm_id}_asee1_sensor1">
    </link>

    <joint name="${arm_id}_asee1_sensor2_joint" type="fixed">
      <origin xyz="-0.058 0 -0.085" rpy="0 -1.570796 0" />
      <parent link="${arm_id}_asee1" />
      <child link="${arm_id}_asee1_sensor2" />
    </joint>
    <link name="${arm_id}_asee1_sensor2">
    </link>

    <joint name="${arm_id}_asee1_sensor3_joint" type="fixed">
      <origin xyz="0 0.058 -0.085" rpy="0 -1.570796 0" />
      <parent link="${arm_id}_asee1" />
      <child link="${arm_id}_asee1_sensor3" />
    </joint>
    <link name="${arm_id}_asee1_sensor3">
    </link>

    <joint name="${arm_id}_asee1_sensor4_joint" type="fixed">
      <origin xyz="0 -0.058 -0.085" rpy="0 -1.570796 0" />
      <parent link="${arm_id}_asee1" />
      <child link="${arm_id}_asee1_sensor4" />
    </joint>
    <link name="${arm_id}_asee1_sensor4">
    </link>

    <gazebo reference="${arm_id}_asee1_sensor1">
      <sensor type="ray" name="sensor1">
        <pose>0 0 0 0 0 0</pose>
        <!-- <visualize>true</visualize> -->
        <update_rate>30</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.00</min>
            <max>0.20</max>
            <resolution>0.001</resolution>
          </range>
          <!-- <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.00001</stddev>
          </noise> -->
        </ray>
        <plugin name="ros_ray_sensor_controller" filename="libgazebo_ros_laser.so">
          <topicName>/asee1/sensor1/laser</topicName>
          <frameName>${arm_id}_asee1_sensor1</frameName>
        </plugin>
      </sensor>
    </gazebo>

    <gazebo reference="${arm_id}_asee1_sensor2">
      <sensor type="ray" name="sensor2">
        <pose>0 0 0 0 0 0</pose>
        <!-- <visualize>true</visualize> -->
        <update_rate>30</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.00</min>
            <max>0.20</max>
            <resolution>0.001</resolution>
          </range>
          <!-- <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.00001</stddev>
          </noise> -->
        </ray>
        <plugin name="ros_ray_sensor_controller" filename="libgazebo_ros_laser.so">
          <topicName>/asee1/sensor2/laser</topicName>
          <frameName>${arm_id}_asee1_sensor2</frameName>
        </plugin>
      </sensor>
    </gazebo>

    <gazebo reference="${arm_id}_asee1_sensor3">
      <sensor type="ray" name="sensor3">
        <pose>0 0 0 0 0 0</pose>
        <!-- <visualize>true</visualize> -->
        <update_rate>30</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.00</min>
            <max>0.20</max>
            <resolution>0.001</resolution>
          </range>
          <!-- <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.00001</stddev>
          </noise> -->
        </ray>
        <plugin name="ros_ray_sensor_controller" filename="libgazebo_ros_laser.so">
          <topicName>/asee1/sensor3/laser</topicName>
          <frameName>${arm_id}_asee1_sensor3</frameName>
        </plugin>
      </sensor>
    </gazebo>

    <gazebo reference="${arm_id}_asee1_sensor4">
      <sensor type="ray" name="sensor4">
        <pose>0 0 0 0 0 0</pose>
        <!-- <visualize>true</visualize> -->
        <update_rate>30</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.00</min>
            <max>0.20</max>
            <resolution>0.001</resolution>
          </range>
          <!-- <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.00001</stddev>
          </noise> -->
        </ray>
        <plugin name="ros_ray_sensor_controller" filename="libgazebo_ros_laser.so">
          <topicName>/asee1/sensor4/laser</topicName>
          <frameName>${arm_id}_asee1_sensor4</frameName>
        </plugin>
      </sensor>
    </gazebo>

  </xacro:macro>
</robot>
